BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE SCHEMA IF NOT EXISTS "identity";
CREATE SCHEMA IF NOT EXISTS payroll;
CREATE SCHEMA IF NOT EXISTS accounting;
CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS reporting;

CREATE TABLE IF NOT EXISTS "identity".rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE,
    descripcion VARCHAR(200),
    nivel_acceso INTEGER NOT NULL DEFAULT 1 CHECK (nivel_acceso > 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_rol_predefinido CHECK (
        nombre IN ('Administrador RRHH', 'Contador', 'Gerente Financiero', 'Administrador Sistema')
    )
);

CREATE TABLE IF NOT EXISTS "identity".usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    nombre_completo VARCHAR(200) NOT NULL,
    id_rol BIGINT NOT NULL REFERENCES "identity".rol(id_rol)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    ultimo_acceso TIMESTAMPTZ,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0 CHECK (intentos_fallidos >= 0),
    bloqueado_hasta TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_usuario_username CHECK (username ~ '^[A-Za-z0-9]{3,50}$'),
    CONSTRAINT ck_usuario_nombre CHECK (btrim(nombre_completo) <> '')
);

CREATE TABLE IF NOT EXISTS "identity".login_attempt (
    id_login_attempt BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT REFERENCES "identity".usuario(id_usuario)
        ON DELETE SET NULL ON UPDATE CASCADE,
    username VARCHAR(50) NOT NULL,
    exitoso BOOLEAN NOT NULL,
    ip_origen INET,
    fecha_intento TIMESTAMPTZ NOT NULL DEFAULT now(),
    correlation_id VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS "identity".token_revocation (
    jti VARCHAR(128) PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES "identity".usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    revocado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    expira_en TIMESTAMPTZ NOT NULL,
    motivo VARCHAR(80) NOT NULL DEFAULT 'Logout',
    correlation_id VARCHAR(64) NOT NULL,
    CONSTRAINT ck_token_revocation_expira CHECK (expira_en > revocado_en)
);

CREATE TABLE IF NOT EXISTS payroll.departamento (
    id_departamento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(250),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_departamento_nombre CHECK (btrim(nombre) <> '')
);

CREATE TABLE IF NOT EXISTS payroll.tipo_descuento (
    id_tipo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL UNIQUE,
    descripcion VARCHAR(200),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_tipo_descuento_nombre CHECK (nombre IN ('AFP', 'ONP'))
);

CREATE TABLE IF NOT EXISTS payroll.config_descuento_previsional_version (
    id_config_descuento_version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo BIGINT NOT NULL REFERENCES payroll.tipo_descuento(id_tipo)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    version INTEGER NOT NULL CHECK (version > 0),
    porcentaje NUMERIC(5,2) NOT NULL CHECK (porcentaje >= 0 AND porcentaje <= 100),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Draft',
    CONSTRAINT uq_config_descuento_version UNIQUE (id_tipo, version),
    CONSTRAINT ck_config_descuento_estado CHECK (estado IN ('Draft', 'Active', 'Closed')),
    CONSTRAINT ck_config_descuento_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ex_config_descuento_no_overlap EXCLUDE USING gist (
        id_tipo WITH =,
        daterange(fecha_inicio, COALESCE(fecha_fin, 'infinity'::DATE), '[]') WITH &&
    ) WHERE (estado = 'Active')
);

CREATE TABLE IF NOT EXISTS payroll.empleado (
    id_empleado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento BIGINT NOT NULL REFERENCES payroll.departamento(id_departamento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_tipo_descuento BIGINT NOT NULL REFERENCES payroll.tipo_descuento(id_tipo)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    dni VARCHAR(8) NOT NULL UNIQUE,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    cargo VARCHAR(80) NOT NULL,
    salario_base NUMERIC(10,2) NOT NULL CHECK (salario_base > 0),
    fecha_nacimiento DATE NOT NULL,
    fecha_ingreso DATE NOT NULL,
    banco VARCHAR(80) NOT NULL,
    numero_cuenta VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_empleado_dni CHECK (dni ~ '^[0-9]{8}$'),
    CONSTRAINT ck_empleado_mayor_edad CHECK (fecha_nacimiento <= CURRENT_DATE - INTERVAL '18 years'),
    CONSTRAINT ck_empleado_fecha_ingreso CHECK (fecha_ingreso <= CURRENT_DATE),
    CONSTRAINT ck_empleado_numero_cuenta CHECK (numero_cuenta ~ '^[0-9]{14,20}$'),
    CONSTRAINT ck_empleado_textos CHECK (
        nombres ~ '^[[:alpha:] ]{2,100}$' AND apellidos ~ '^[[:alpha:] ]{2,100}$' AND
        btrim(cargo) <> '' AND btrim(banco) <> ''
    )
);

CREATE TABLE IF NOT EXISTS payroll.horas_extra (
    id_horas_extra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado BIGINT NOT NULL REFERENCES payroll.empleado(id_empleado)
        ON DELETE CASCADE ON UPDATE CASCADE,
    periodo VARCHAR(10) NOT NULL,
    horas_primeras_dos NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (horas_primeras_dos >= 0),
    horas_posteriores NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (horas_posteriores >= 0),
    estado VARCHAR(20) NOT NULL DEFAULT 'Draft',
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_aprobacion TIMESTAMPTZ,
    id_usuario_aprobador BIGINT REFERENCES "identity".usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT uq_horas_extra_empleado_periodo UNIQUE (id_empleado, periodo),
    CONSTRAINT ck_horas_extra_periodo CHECK (periodo ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT ck_horas_extra_estado CHECK (estado IN ('Draft', 'Approved', 'Cancelled')),
    CONSTRAINT ck_horas_extra_valores CHECK (horas_primeras_dos + horas_posteriores > 0),
    CONSTRAINT ck_horas_extra_aprobacion CHECK (
        estado <> 'Approved' OR (fecha_aprobacion IS NOT NULL AND id_usuario_aprobador IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS payroll.periodo_planilla (
    id_periodo_planilla BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo VARCHAR(10) NOT NULL UNIQUE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Draft',
    total_bruto NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total_bruto >= 0),
    total_descuentos NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total_descuentos >= 0),
    total_neto NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total_neto >= 0),
    total_provision_gratificacion NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total_provision_gratificacion >= 0),
    total_provision_cts NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total_provision_cts >= 0),
    fecha_calculo TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_finalizacion TIMESTAMPTZ,
    id_usuario_finalizador BIGINT REFERENCES "identity".usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_periodo_planilla_formato CHECK (periodo ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT ck_periodo_planilla_estado CHECK (estado IN ('Draft', 'Finalized', 'Cancelled')),
    CONSTRAINT ck_periodo_planilla_neto CHECK (total_neto = total_bruto - total_descuentos),
    CONSTRAINT ck_periodo_planilla_finalizacion CHECK (
        estado <> 'Finalized' OR (fecha_finalizacion IS NOT NULL AND id_usuario_finalizador IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS payroll.planilla (
    id_planilla BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_periodo_planilla BIGINT NOT NULL REFERENCES payroll.periodo_planilla(id_periodo_planilla)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_empleado BIGINT NOT NULL REFERENCES payroll.empleado(id_empleado)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_departamento BIGINT NOT NULL REFERENCES payroll.departamento(id_departamento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    salario_base_aplicado NUMERIC(10,2) NOT NULL CHECK (salario_base_aplicado > 0),
    total_bruto NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total_bruto >= 0),
    total_descuentos NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total_descuentos >= 0),
    total_neto NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total_neto >= 0),
    CONSTRAINT uq_planilla_periodo_empleado UNIQUE (id_periodo_planilla, id_empleado),
    CONSTRAINT ck_planilla_neto CHECK (total_neto = total_bruto - total_descuentos)
);

CREATE TABLE IF NOT EXISTS payroll.detalle_planilla (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_planilla BIGINT NOT NULL UNIQUE REFERENCES payroll.planilla(id_planilla)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_config_descuento_version BIGINT NOT NULL REFERENCES payroll.config_descuento_previsional_version(id_config_descuento_version)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    horas_extra_total NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (horas_extra_total >= 0),
    afp NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (afp >= 0),
    onp NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (onp >= 0),
    provision_cts NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (provision_cts >= 0),
    provision_gratificacion NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (provision_gratificacion >= 0),
    descuentos_adicionales NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (descuentos_adicionales = 0)
);

CREATE TABLE IF NOT EXISTS admin.config_tributaria_version (
    id_config_tributaria_version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(250),
    version INTEGER NOT NULL CHECK (version > 0),
    tasa_igv NUMERIC(5,2) NOT NULL CHECK (tasa_igv >= 0 AND tasa_igv <= 100),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Draft',
    CONSTRAINT uq_config_tributaria_codigo_version UNIQUE (codigo, version),
    CONSTRAINT ck_config_tributaria_codigo CHECK (codigo = 'IGV'),
    CONSTRAINT ck_config_tributaria_estado CHECK (estado IN ('Draft', 'Active', 'Closed')),
    CONSTRAINT ck_config_tributaria_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ex_config_tributaria_no_overlap EXCLUDE USING gist (
        codigo WITH =,
        daterange(fecha_inicio, COALESCE(fecha_fin, 'infinity'::DATE), '[]') WITH &&
    ) WHERE (estado = 'Active')
);

CREATE TABLE IF NOT EXISTS admin.config_sunat_formato (
    id_config_sunat_formato BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_libro VARCHAR(20) NOT NULL,
    version_formato VARCHAR(20) NOT NULL,
    estructura_json JSONB NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'Draft',
    CONSTRAINT uq_config_sunat_formato_version UNIQUE (tipo_libro, version_formato),
    CONSTRAINT ck_config_sunat_tipo CHECK (tipo_libro IN ('Compras', 'Ventas')),
    CONSTRAINT ck_config_sunat_version CHECK (btrim(version_formato) <> ''),
    CONSTRAINT ck_config_sunat_estado CHECK (estado IN ('Draft', 'Active', 'Closed')),
    CONSTRAINT ck_config_sunat_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ck_config_sunat_estructura CHECK (
        jsonb_typeof(estructura_json) = 'object' AND
        (estructura_json - 'columns') = '{}'::JSONB AND
        jsonb_typeof(estructura_json -> 'columns') = 'array' AND
        jsonb_array_length(estructura_json -> 'columns') = 11 AND
        estructura_json -> 'columns' @> '["periodo","tipoDocumento","numeroDocumento","tipoComprobante","serie","numero","fechaEmision","baseImponible","baseExonerada","igv","total"]'::JSONB
    ),
    CONSTRAINT ex_config_sunat_no_overlap EXCLUDE USING gist (
        tipo_libro WITH =,
        daterange(fecha_inicio, COALESCE(fecha_fin, 'infinity'::DATE), '[]') WITH &&
    ) WHERE (estado = 'Active')
);

CREATE TABLE IF NOT EXISTS admin.empresa (
    id_empresa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL UNIQUE,
    razon_social VARCHAR(200) NOT NULL,
    nombre_comercial VARCHAR(200),
    domicilio_fiscal VARCHAR(300) NOT NULL,
    regimen VARCHAR(50) NOT NULL DEFAULT 'Regimen MYPE Tributo Especial',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_empresa_ruc CHECK (ruc ~ '^[0-9]{11}$'),
    CONSTRAINT ck_empresa_razon CHECK (btrim(razon_social) <> ''),
    CONSTRAINT ck_empresa_domicilio CHECK (btrim(domicilio_fiscal) <> ''),
    CONSTRAINT ck_empresa_regimen CHECK (regimen IN (
        'Regimen MYPE Tributo Especial',
        'Regimen General',
        'Otro'
    ))
);

CREATE TABLE IF NOT EXISTS accounting.tipo_comprobante (
    id_tipo_comp BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL UNIQUE,
    codigo_sunat VARCHAR(4) NOT NULL UNIQUE,
    afecto_igv BOOLEAN NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_tipo_comprobante_textos CHECK (btrim(nombre) <> '' AND btrim(codigo_sunat) <> '')
);

CREATE TABLE IF NOT EXISTS accounting.comprobante (
    id_comprobante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_comp BIGINT NOT NULL REFERENCES accounting.tipo_comprobante(id_tipo_comp)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_config_tributaria_version BIGINT NOT NULL REFERENCES admin.config_tributaria_version(id_config_tributaria_version)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_comprobante_referencia BIGINT REFERENCES accounting.comprobante(id_comprobante)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    tipo_movimiento VARCHAR(10) NOT NULL,
    tipo_documento VARCHAR(10) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL,
    razon_social VARCHAR(200) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    fecha_emision DATE NOT NULL,
    base_imponible NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (base_imponible >= 0),
    base_exonerada NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (base_exonerada >= 0),
    igv NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (igv >= 0),
    total NUMERIC(10,2) NOT NULL CHECK (total > 0),
    tipo_operacion VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Registrado',
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_comprobante_identidad UNIQUE (id_tipo_comp, tipo_movimiento, serie, numero),
    CONSTRAINT ck_comprobante_movimiento CHECK (tipo_movimiento IN ('Compra', 'Venta')),
    CONSTRAINT ck_comprobante_tipo_documento CHECK (tipo_documento IN ('RUC', 'DNI', 'Otro')),
    CONSTRAINT ck_comprobante_documento_ruc CHECK (tipo_documento <> 'RUC' OR numero_documento ~ '^[0-9]{11}$'),
    CONSTRAINT ck_comprobante_documento_dni CHECK (tipo_documento <> 'DNI' OR numero_documento ~ '^[0-9]{8}$'),
    CONSTRAINT ck_comprobante_operacion CHECK (tipo_operacion IN ('Gravada', 'Exonerada', 'Inafecta')),
    CONSTRAINT ck_comprobante_estado CHECK (estado IN ('Registrado', 'Anulado')),
    CONSTRAINT ck_comprobante_no_autoreferencia CHECK (
        id_comprobante_referencia IS NULL OR id_comprobante_referencia <> id_comprobante
    ),
    CONSTRAINT ck_comprobante_textos CHECK (
        btrim(numero_documento) <> '' AND btrim(razon_social) <> '' AND
        btrim(serie) <> '' AND btrim(numero) <> ''
    ),
    CONSTRAINT ck_comprobante_base_positiva CHECK (base_imponible > 0 OR base_exonerada > 0),
    CONSTRAINT ck_comprobante_total CHECK (total = base_imponible + base_exonerada + igv)
);

CREATE TABLE IF NOT EXISTS accounting.tipo_libro (
    id_tipo_libro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_tipo_libro_nombre CHECK (nombre IN ('Compras', 'Ventas'))
);

CREATE TABLE IF NOT EXISTS accounting.libro_contable (
    id_libro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_libro BIGINT NOT NULL REFERENCES accounting.tipo_libro(id_tipo_libro)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_config_sunat_formato BIGINT NOT NULL REFERENCES admin.config_sunat_formato(id_config_sunat_formato)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_usuario_generador BIGINT NOT NULL REFERENCES "identity".usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    periodo VARCHAR(10) NOT NULL,
    version INTEGER NOT NULL CHECK (version > 0),
    fecha_generacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    estado VARCHAR(20) NOT NULL DEFAULT 'Generado',
    total_base_imponible NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_base_imponible >= 0),
    total_igv NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_igv >= 0),
    total_general NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_general >= 0),
    CONSTRAINT uq_libro_tipo_periodo_version UNIQUE (id_tipo_libro, periodo, version),
    CONSTRAINT ck_libro_periodo CHECK (periodo ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT ck_libro_estado CHECK (estado = 'Generado')
);

CREATE TABLE IF NOT EXISTS accounting.comprobante_libro (
    id_libro BIGINT NOT NULL REFERENCES accounting.libro_contable(id_libro)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_comprobante BIGINT NOT NULL REFERENCES accounting.comprobante(id_comprobante)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_config_tributaria_version BIGINT NOT NULL REFERENCES admin.config_tributaria_version(id_config_tributaria_version)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    orden INTEGER NOT NULL CHECK (orden > 0),
    periodo VARCHAR(10) NOT NULL,
    tipo_documento VARCHAR(10) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL,
    codigo_tipo_comprobante VARCHAR(4) NOT NULL,
    serie VARCHAR(10) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    fecha_emision DATE NOT NULL,
    base_imponible NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (base_imponible >= 0),
    base_exonerada NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (base_exonerada >= 0),
    total_igv NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_igv >= 0),
    total_general NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_general >= 0),
    PRIMARY KEY (id_libro, id_comprobante),
    CONSTRAINT uq_comprobante_libro_orden UNIQUE (id_libro, orden)
);

CREATE TABLE IF NOT EXISTS accounting.periodo_contable (
    id_periodo_contable BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Open',
    fecha_cierre TIMESTAMPTZ,
    id_usuario_cierre BIGINT REFERENCES "identity".usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_periodo_codigo CHECK (codigo ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
    CONSTRAINT ck_periodo_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_periodo_estado CHECK (estado IN ('Open', 'Closed')),
    CONSTRAINT ck_periodo_cierre CHECK (
        (estado = 'Closed') = (fecha_cierre IS NOT NULL AND id_usuario_cierre IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS accounting.cuenta_contable (
    id_cuenta_contable BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    naturaleza VARCHAR(10) NOT NULL,
    id_cuenta_padre BIGINT REFERENCES accounting.cuenta_contable(id_cuenta_contable)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_cuenta_textos CHECK (btrim(codigo) <> '' AND btrim(nombre) <> ''),
    CONSTRAINT ck_cuenta_tipo CHECK (tipo IN ('Asset', 'Liability', 'Equity', 'Income', 'Expense', 'Cost')),
    CONSTRAINT ck_cuenta_naturaleza CHECK (naturaleza IN ('Debit', 'Credit'))
);

CREATE TABLE IF NOT EXISTS accounting.asiento_contable (
    id_asiento_contable BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_periodo_contable BIGINT NOT NULL REFERENCES accounting.periodo_contable(id_periodo_contable)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_asiento_revertido BIGINT REFERENCES accounting.asiento_contable(id_asiento_contable)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    fecha_asiento DATE NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    origen VARCHAR(30) NOT NULL DEFAULT 'Manual',
    id_origen BIGINT,
    estado VARCHAR(20) NOT NULL DEFAULT 'Draft',
    fecha_posteo TIMESTAMPTZ,
    id_usuario_posteo BIGINT REFERENCES "identity".usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_asiento_origen CHECK (origen IN ('Manual', 'Comprobante', 'Planilla', 'Ajuste')),
    CONSTRAINT ck_asiento_descripcion CHECK (btrim(descripcion) <> ''),
    CONSTRAINT ck_asiento_estado CHECK (estado IN ('Draft', 'Posted', 'Cancelled')),
    CONSTRAINT ck_asiento_posteo CHECK (
        (estado = 'Posted') = (fecha_posteo IS NOT NULL AND id_usuario_posteo IS NOT NULL)
    ),
    CONSTRAINT ck_asiento_reversion CHECK (
        (origen = 'Ajuste' AND id_asiento_revertido IS NOT NULL) OR
        (origen <> 'Ajuste' AND id_asiento_revertido IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_asiento_origen
    ON accounting.asiento_contable(origen, id_origen)
    WHERE origen IN ('Comprobante', 'Planilla');

CREATE UNIQUE INDEX IF NOT EXISTS uq_asiento_reversion_activa
    ON accounting.asiento_contable(id_asiento_revertido)
    WHERE id_asiento_revertido IS NOT NULL AND estado <> 'Cancelled';

CREATE TABLE IF NOT EXISTS accounting.detalle_asiento (
    id_detalle_asiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asiento_contable BIGINT NOT NULL REFERENCES accounting.asiento_contable(id_asiento_contable)
        ON DELETE CASCADE ON UPDATE CASCADE,
    id_cuenta_contable BIGINT NOT NULL REFERENCES accounting.cuenta_contable(id_cuenta_contable)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    debe NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (debe >= 0),
    haber NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (haber >= 0),
    descripcion VARCHAR(250),
    CONSTRAINT ck_detalle_asiento_lado CHECK (
        (debe > 0 AND haber = 0) OR (haber > 0 AND debe = 0)
    )
);

CREATE TABLE IF NOT EXISTS reporting.reporte_snapshot (
    id_reporte_snapshot BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_reporte VARCHAR(30) NOT NULL,
    formato VARCHAR(10) NOT NULL,
    periodo_desde VARCHAR(10) NOT NULL,
    periodo_hasta VARCHAR(10) NOT NULL,
    id_departamento BIGINT REFERENCES payroll.departamento(id_departamento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    id_usuario BIGINT NOT NULL REFERENCES "identity".usuario(id_usuario)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    rol_actor VARCHAR(30) NOT NULL,
    filtros_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    totales_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    fuente_corte TIMESTAMPTZ NOT NULL,
    fecha_generacion TIMESTAMPTZ NOT NULL DEFAULT now(),
    estado VARCHAR(20) NOT NULL,
    archivo_referencia VARCHAR(500),
    correlation_id VARCHAR(64) NOT NULL,
    CONSTRAINT ck_reporte_tipo CHECK (tipo_reporte IN ('BalanceGeneral', 'EstadoResultados', 'PlanillaConsolidada')),
    CONSTRAINT ck_reporte_formato CHECK (formato IN ('PDF', 'Excel')),
    CONSTRAINT ck_reporte_estado CHECK (estado IN ('Generated', 'Failed')),
    CONSTRAINT ck_reporte_archivo CHECK (
        estado <> 'Generated' OR (archivo_referencia IS NOT NULL AND btrim(archivo_referencia) <> '')
    ),
    CONSTRAINT ck_reporte_periodos CHECK (
        periodo_desde ~ '^[0-9]{4}-(0[1-9]|1[0-2])$' AND
        periodo_hasta ~ '^[0-9]{4}-(0[1-9]|1[0-2])$' AND
        periodo_hasta >= periodo_desde
    )
);

CREATE TABLE IF NOT EXISTS reporting.reporte_linea (
    id_reporte_linea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reporte_snapshot BIGINT NOT NULL REFERENCES reporting.reporte_snapshot(id_reporte_snapshot)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    orden INTEGER NOT NULL CHECK (orden > 0),
    codigo VARCHAR(50) NOT NULL,
    etiqueta VARCHAR(200) NOT NULL,
    monto NUMERIC(14,2) NOT NULL,
    datos_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    CONSTRAINT uq_reporte_linea_orden UNIQUE (id_reporte_snapshot, orden),
    CONSTRAINT ck_reporte_linea_textos CHECK (btrim(codigo) <> '' AND btrim(etiqueta) <> '')
);

CREATE TABLE IF NOT EXISTS audit.audit_log (
    id_audit_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT REFERENCES "identity".usuario(id_usuario)
        ON DELETE SET NULL ON UPDATE CASCADE,
    rol_actor VARCHAR(30),
    modulo VARCHAR(50) NOT NULL,
    accion VARCHAR(80) NOT NULL,
    entidad VARCHAR(80) NOT NULL,
    id_entidad VARCHAR(50),
    resultado VARCHAR(20) NOT NULL,
    datos_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    fecha_evento TIMESTAMPTZ NOT NULL DEFAULT now(),
    correlation_id VARCHAR(64) NOT NULL,
    CONSTRAINT ck_audit_resultado CHECK (resultado IN ('Success', 'Failure', 'Blocked')),
    CONSTRAINT ck_audit_actor CHECK (id_usuario IS NULL OR rol_actor IS NOT NULL)
);

COMMIT;
